/**
 * PWA Splash Screen — auto-generated by LogoNuri
 * Generates iOS splash screens at runtime for the current device.
 *
 * Usage: Include this script in your <head> after your apple-touch-icon link tag.
 *
 * Note: On the very first cold install of a PWA, iOS may show a white screen
 * because startup images are read before JS executes. Splash screens activate
 * after the first app launch once the browser has cached the link tags.
 */
(function(){
function run(){
try{
// Remove any existing startup images (prevent duplicates on re-run)
document.querySelectorAll('link[rel="apple-touch-startup-image"]').forEach(function(el){el.remove()});

// Check sessionStorage cache (optimization — not required for correctness)
var cp=null,cl=null;
try{cp=sessionStorage.getItem("__pwa_splash_p");cl=sessionStorage.getItem("__pwa_splash_l")}catch(e){}
if(cp&&cl){inject(cp,"portrait");inject(cl,"landscape");ensureMeta();return}

// Detect device
var dw=screen.width,dh=screen.height,dpr=window.devicePixelRatio||1;
var pw=dw*dpr,ph=dh*dpr;
var bg="#ffffff";

// Find apple-touch-icon in the document
var iconEl=document.querySelector('link[rel="apple-touch-icon"]');
var iconSrc=iconEl?iconEl.href:null;

function generateAndInject(icon){
var c1=document.createElement("canvas"),c2=document.createElement("canvas");
c1.width=pw;c1.height=ph;c2.width=ph;c2.height=pw;
var x1=c1.getContext("2d"),x2=c2.getContext("2d");
x1.fillStyle=bg;x2.fillStyle=bg;
x1.fillRect(0,0,pw,ph);x2.fillRect(0,0,ph,pw);

if(icon){
var s=Math.min(pw,ph)*0.25;
var sc=Math.min(s/icon.naturalWidth,s/icon.naturalHeight);
var iw=icon.naturalWidth*sc,ih=icon.naturalHeight*sc;
x1.drawImage(icon,(pw-iw)/2,(ph-ih)/2,iw,ih);
x2.drawImage(icon,(ph-iw)/2,(pw-ih)/2,iw,ih);
}

var d1=c1.toDataURL("image/png"),d2=c2.toDataURL("image/png");
try{sessionStorage.setItem("__pwa_splash_p",d1);sessionStorage.setItem("__pwa_splash_l",d2)}catch(e){}
inject(d1,"portrait");inject(d2,"landscape");ensureMeta();
}

if(iconSrc){
var img=new Image();img.crossOrigin="anonymous";
img.onload=function(){generateAndInject(img)};
img.onerror=function(){generateAndInject(null)};
img.src=iconSrc;
}else{
generateAndInject(null);
}

function inject(href,orient){
var l=document.createElement("link");
l.rel="apple-touch-startup-image";
l.media="screen and (orientation: "+orient+")";
l.href=href;
document.head.appendChild(l);
}

function ensureMeta(){
if(!document.querySelector('meta[name="apple-mobile-web-app-capable"]')){
var m=document.createElement("meta");m.name="apple-mobile-web-app-capable";m.content="yes";
document.head.appendChild(m);
}
}

}catch(e){if(typeof console!=="undefined")console.warn("PWA splash error:",e)}
}
if(document.readyState==="loading"){
document.addEventListener("DOMContentLoaded",run,{once:true});
}else{
run();
}
})();